<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "root");
if (!defined("PJ_PASS")) define("PJ_PASS", "Bpc@1404");
if (!defined("PJ_DB")) define("PJ_DB", "ticketbooking");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "tk_");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/projects/ticketatgurumaster/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "E:/xampp/htdocs/projects/ticketatgurumaster/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "http://103.121.156.221/projects/ticketatgurumaster/");
if (!defined("PJ_SALT")) define("PJ_SALT", "GYZG3G97");//*N6EZGZ3Q
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTEzNzQ5MTMwNDc1MjM0NTA2MTk1OTE0OTI2MDU5NDI4OTAxNTg4NDc4NDUwNDY1NTQzMDE2MzU3NDU3NDY2ODUzOTU5NzQ0MjQ5MDQ1MzAzMDUxOTU1Njg3Nzc4ODA2NDMwMiAxMjgyNTc4MjM3MDM2OTU3MDQwMDkyNTM3MTUxOTY4MjYxOTgwMjI1ODg3NTk0Mjg2NzUxNTE3MzQzODY4MzM1MDI1NjU1NDI2NzM0NzkwMTU4NzQyOTg0OTM3ODgwMjM3OTY1IDE0MzA2MDMyNzI2NjI1MzQ0ODY3MDczMDQ1MDA0MDU3MDEzNTUyNTE1MDA2NDc0NzgzNTM5NDQ1NzU3MzM5NzI3MTA3MDc5MDY1MzMyNjAyNDYyMjEyNjk2NjAxMDUzMTM2NzAgMzEzMjg3NjM2ODk5NDYyMTI5NzM3NTUyMzMxMTI0NDY5MzI1NzMwMjQxNzc1NTEyNzAwNTQ4NDkwMDMyNTQ3NjM5NzEzMjM4MjAwODQyNzc5NDAzNDYwMzc1MTk0NDcxMTczIDI3MDY1NzY4MjEwMTQ5ODU5OTE2MTg4MTA0MTYxODQyNDQzNDM1MzcyMjQ4MDE1OTQ4MTQ2MTgyNDI0ODcxOTU0NjIwMTE5NzQ4NTQ5NzUwMDAwNjQ3NDA1ODE3MjQ3NDA1");
?>
<?php
$CONFIG['plugins'] = 'pjPaypal';
?>